import event1 from "../media/banksy.png";
import event2 from "../media/banksy.png";
import event3 from "../media/banksy.png";
import event4 from "../media/banksy.png";
import event5 from "../media/banksy.png";
import event6 from "../media/banksy.png";
import event7 from "../media/banksy.png";
import event8 from "../media/banksy.png";

export const EVENT_NFTS = [
  {
    id: 1,
    img: event1,
    description: "This is the description event with lots of marketing stuff.",
    evtTitle1: "The Merge",
    evtTitle2: "Ethereum Live: The Merge",
    location: "Crypto.com Arena",
    date: "15 Sep",
    price: 1534,
    duration: "10:00 PM - 01:00 AM",
    ownerName: "Garo",
    ownerAvatar: "",
  },
  {
    id: 2,
    img: event2,
    description: "This is the description event with lots of marketing stuff.",
    evtTitle1: "The ChainLinkers",
    evtTitle2: "Ethereum Live: The Merge",
    location: "Crypto.com Arena",
    date: "22 Sep",
    price: 250,
    duration: "10:00 PM - 01:00 AM",
    ownerName: "Constantino",
    ownerAvatar: "",
  },
  {
    id: 3,
    img: event3,
    description: "This is the description event with lots of marketing stuff.",
    evtTitle1: "Green Day",
    evtTitle2: "Ethereum Live: The Merge",
    location: "Crypto.com Arena",
    date: "1 Oct",
    price: 200,
    duration: "10:00 PM - 01:00 AM",
    ownerName: "Isaac",
    ownerAvatar: "",
  },
  {
    id: 4,
    img: event4,
    description: "This is the description event with lots of marketing stuff.",
    evtTitle1: "Bad Bunny",
    evtTitle2: "Ethereum Live: The Merge",
    location: "Crypto.com Arena",
    date: "10 Oct",
    price: 100,
    duration: "10:00 PM - 01:00 AM",
    ownerName: "Andrés",
    ownerAvatar: "",
  },
  {
    id: 5,
    img: event5,
    description: "This is the description event with lots of marketing stuff.",
    evtTitle1: "The Strokes",
    evtTitle2: "Ethereum Live: The Merge",
    location: "Crypto.com Arena",
    date: "20 Oct",
    price: 1000,
    duration: "10:00 PM - 01:00 AM",
    ownerName: "Andrés",
    ownerAvatar: "",
  },
  {
    id: 6,
    img: event6,
    description: "This is the description event with lots of marketing stuff.",
    evtTitle1: "The Merge",
    evtTitle2: "Ethereum Live: The Merge",
    location: "Crypto.com Arena",
    date: "30 Oct",
    price: 500,
    duration: "10:00 PM - 01:00 AM",
    ownerName: "Isaac",
    ownerAvatar: "",
  },
  {
    id: 7,
    img: event7,
    description: "This is the description event with lots of marketing stuff.",
    evtTitle1: "The Merge",
    evtTitle2: "Ethereum Live: The Merge",
    location: "Crypto.com Arena",
    date: "5 Nov",
    price: 400,
    duration: "10:00 PM - 01:00 AM",
    ownerName: "Constantino",
    ownerAvatar: "",
  },
  {
    id: 8,
    img: event8,
    description: "This is the description event with lots of marketing stuff.",
    evtTitle1: "The ETHKillers",
    evtTitle2: "",
    location: "Crypto.com Arena",
    date: "1 Apr",
    price: 450,
    duration: "10:00 PM - 01:00 AM",
    ownerName: "Garo",
    ownerAvatar: "",
  },
];
